### ISSUE TITLE
How do we use GitHub milestones (and/or Releases) wrt this repo and generally?

### ISSUE THREAD

**Issue by pirog** [thinktandem/tandem#21] opened 2019-07-01 01:02 UTC
## Prompt

Currently we have a milestone set for the next few months 
https://github.com/thinktandem/tandem/milestones

We also have a ZenHub release that more or less tracks the same thing
https://github.com/thinktandem/tandem/issues#workspaces/tandem-5d0cb0c025117c7c06ea41c6/reports/release?release=5d1958b5dc35883a384b4ac2

They both seem important to have for different reasons but i am not sure how we should differentiate the two. In my mind it makes sense for "releases" to track a strict "version" bump that may or may not track one-to-one with the duration of a milestone(s). Milestones seem like more "human readable" goals that can potentially span multiple releases. Said another way, _Releases track sprints_ and _Milestones_ track "larger things" eg an epic, phase, goal, etc. 

That is purely intuition on my part so i would love feedback, suggestions or just an outright "nah brah this is how you do it" so we can get some tasks on the board to advance this.

The goal in my mind is we need to clearly define how milestones and releases work, interact with one another etc. We need this both for this repo in particular but also all our other projects. Knowing this should help improve our ability to estimate sprints, velocity, etc and also set up longer phases that happen in all our projects. At the very least it gives us some common language and units with which to talk about other things.

## Ticket Checklist

Make sure you complete the following checklist

- [x] I'm aware of [what a discussion actually entails](https://docs.thinktandem.io/guides/improve-tandem.html#suggesting-a-change)
- [x] I've selected _at most_ two labels that _best_ describe what part of the business this ticket improves eg `sales`, `dev`, etc

**Comment by serundeputy** [comment] 2019-07-01 13:35
> In my mind it makes sense for "releases" to track a strict "version" bump that may or may not track one-to-one with the duration of a milestone(s). Milestones seem like more "human readable" goals that can potentially span multiple releases. Said another way, Releases track sprints and Milestones track "larger things" eg an epic, phase, goal, etc

* This is how we manage it in the `backdrop/backdrop-issues` queue not suggesting that we have to adopt this here, but one possible model
  * Tag issue(s) with a milestone (which basically means a sprint and an intent to finish that issue for release X)
  * If an issue is not finished by the time release X happens then the issue is either bumped to the next release cycle patch release for bugs, minor release for features, or deprioritized (i.e. ice boxed if the importance level either changed or was overestimated in the first place)

So in those terms:
  * a sprint or milestone is an intended target for a release
  * a release is what made it from sprint to completion (committed)
  * triage happens post/during every release moving things to the next appropriate milestone or removing milestone all together

**Comment by pirog** [comment] 2019-07-06 02:36
We discussed this internally and we are thinking the following breakdown

1. GitHub milestones should be used to track "sprints" 
2. ZenHub "releases" should be used to track "larger initiatives" 

The language around this is a little bit confusing if you are coming from a strict developer/engineering background but let's give it a shot. Example milestones might be best expressed as version numbers or dates, some standardized form. Releases should be human readable thing like "Architecture phase" or "Documentation Pass".

**Comment by pirog** [comment] 2019-07-06 02:44
@dustinleblanc no PR for this since its a discussion. I did create a follow up task which i think should be sufficient to close this thing out
https://github.com/thinktandem/tandem/issues/46

**Closed** 2019-07-30 18:47 UTC
Labels: discussion, operations, repo
